# Generated by Django 4.1.7 on 2023-02-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
